### ISSUE TITLE
Fail on console.log and others

### ISSUE THREAD

**Issue by andi0b** [nils-hoyer/cypress-fail-on-console-error#294]
It would be great if there were more spy options for console, and not only warn, error and info. Especially console.log is commonly used for debugging and should not end up in a production release. I know there are other ways to prevent this, but it's also nice to let e2e tests fail, if anything is written to console.log.

Other interesting methods would include:
- console.debug()
- console.trace()
- console.table()

**Comment by nils-hoyer** [comment]
Hi @andi0b,

this should be quite simple to add. let me have a look.

**Comment by nils-hoyer** [comment]
With a small delay I just released [version 5.1.0](https://www.npmjs.com/package/cypress-fail-on-console-error/v/5.1.0.) including observing for console.debug(), console.trace() and console.table(). Its verified and tested for cypress e2e. For cypress component testing I had some issues. It might not be stable yet. Issues are created https://github.com/nils-hoyer/cypress-fail-on-console-error/issues/319 https://github.com/nils-hoyer/cypress-fail-on-console-error/issues/318 https://github.com/nils-hoyer/cypress-fail-on-console-error/issues/317 .

**Comment by andi0b** [comment]
@nils-hoyer great, thanks! I might use that in the future.

But may I ask if there is a reason that console.log() - in my opinion by far the most common one - is still not supported?
